### ISSUE TITLE
singlet integration

### ISSUE THREAD

**Issue by iosonofabio** [atarashansky/self-assembling-manifold#1]
Hi Alec,

So I'm thinking of including SAM into my [singlet](https://github.com/iosonofabio/singlet) for my and your convenience. What you gain is that this will force you to file edges for your users whether or not they use singlet at all.

If you are interested, here's what needs to happen:
 - Travis integration of Python 3.4+ on Linux and 3.6/3.7 on OSX - can help you with that via a PR
 - Minimal running instructions in the README - that's easy
 - Your tutorial currently requires SAM to read tables from file. That's bad design and needs to change, all you need is a matrix of counts, you should not force a specific data storage implementation (e.g. a file). Instead, you need to delegate the marshalling from file to a separate function and set up an entry point into the SAM class that does not depend on files. For instance, singlet accepts both an easy string that refers to a config file *or* a pre-loaded matrix table.

Obviously the last point is the relevant one. Once I can inject my matrix table into the SAM constructor, integration within singlet, scanpy, or whatever else is going to be trivial.

What do you think?

**Comment by atarashansky** [comment]
Thanks so much, Fabio! I'd appreciate the help for the Travis CI integration. As for the pre-loaded matrix table, may I assume that it is a pandas dataframe, or would you prefer I expect a scipy sparse / numpy matrix with gene and cell IDs provided separately?

**Comment by iosonofabio** [comment]
Awesome!

The matrix can be a dataframe for now, or you can subclass dataframes if you prefer to have more control upstream (that's how I did it in singlet - it's not great but ok). I can help you with that one of these days if you want.

**Comment by iosonofabio** [comment]
I'll fork your repo and start a stub travis later this week or early next week

**Comment by atarashansky** [comment]
Simply loading a vanilla dataframe is perfect since it would require minimal restructuring of the code. I'll update the repo today or tomorrow.

**Comment by iosonofabio** [comment]
sounds good, you do that then write here and I'll fork from there. Also just talked to Soso, seems ok

**Comment by atarashansky** [comment]
I made the suggested changes to SAM.py and updated the readme file with basic usage examples.

**Comment by iosonofabio** [comment]
ok, the code looks still quite rough on the linting side but that's not the topic of this issue. I'll fork and PR some travis

**Comment by iosonofabio** [comment]
fork and PR'ed, please:
- merge
- add a travis webhook if you want (using the travis website) and adapt badge link
- set up a few tests either manually in a `test` folder

Once basic tests are in place I'll integrate into singlet, it's gonna take a minute.

Also, hard dependency on `matplotlib` is a no no, just fail graciously with a warning about missing plot functionality is the user has no `matplotlib` (e.g. running on a headless machine)

**Comment by atarashansky** [comment]
Thanks! I'll work on this later today and will also remove the hard dependency. Although not the topic of issue, any other rules of thumb I should follow to improve the code on the linting side?

**Comment by iosonofabio** [comment]
PEP8-ing helps, there are even programs that pep8 your code for you. Here's a few obvious things I noticed:
- space between instance methods is 1 line, not 2
- constructor should not set `self.ann = annotations`, rather `self.annotations = annotations` (I know...  right?)
- `load_data_from_file` should probably be a class method, not an instance method... you are creating the instance after all, something like
```python
sam = SAM.load_data_from_file('myfile.tsv')
```
- lines longer than 80 characters are discoraged... I know...

**Comment by atarashansky** [comment]
Thanks so much! I'll keep working on it!

**Comment by iosonofabio** [comment]
any progress on this? It's be best to kill it fast to not lose momentum

**Comment by atarashansky** [comment]
Travis CI is working now. I included a basic test script (test/test_sam.py) and updated the .travis_test.sh file. One of my dependencies is incompatible with python3.4 so I removed that from the .yml file for now (I think llvmlite was the culprit but I'm not sure).

**Comment by iosonofabio** [comment]
working but failing, that's great. Let me know if you need support to get the thing to pass tests. yes llvmlite is a beast.

**Comment by atarashansky** [comment]
Seems I'm getting a 'version `GLIBCXX_3.4.21' not found' error for python 3.6 when trying to run the louvain package.

**Comment by iosonofabio** [comment]
try looking at the travis of that package then

**Comment by atarashansky** [comment]
The build passed, now. I had to change the python 3.6 test distribution to xenial.

**Comment by iosonofabio** [comment]
great! Is the current version released on Pypi already? If so I can start the singlet integration and tell people to install it via `pip`.

**Comment by atarashansky** [comment]
Just uploaded the current version to Pypi (version 0.1.8). Thanks!

**Comment by iosonofabio** [comment]
Ok, I'll integrate this into singlet and let you know. Thanks!

**Comment by iosonofabio** [comment]
finished in iosonofabio/singlet@f2e45a9, closing
