### ISSUE TITLE
help with removing clusters from clustering analysis

### ISSUE THREAD

**Issue by pythonhelp** [atarashansky/self-assembling-manifold#11]
Hi - I was hoping to get some help in figuring out how to remove a cluster from my analysis. I have named my clusters: cluster_0 = sam.cell_names[sam.cluster_labels == 0]....but I don't know how to proceed to remove cluster 0 from my analysis. Any suggestions? Thanks

**Comment by atarashansky** [comment]
Hi there!

Happy to help --

If you are using SAMsparse, you can do:
`sam.filter_sparse_data(cells=sam.all_cell_names[np.in1d(sam.all_cell_names,cluster_0,invert=True)])`
(`np` is the `numpy` package)

If you are using SAM, you can do:
`sam.filter_data(cells=sam.cell_names[np.in1d(sam.cell_names,cluster_0,invert=True)])`

After filtering the data, you can use `sam.run` to run SAM on the newly filtered data.

Mind you, SAMsparse will soon replace SAM, so I recommend switching over to that if you're not already on it.

I'll add a feature to to the filter function to exclude cells to make this easier!

Let me know if you have any other issues!

**Comment by pythonhelp** [comment]
Thanks so much for your help and suggestions!

**Comment by pythonhelp** [comment]
Hi again,

When I ran the the program initially with your suggestion below, it worked. However, when I went to run it again this morning....it no longer worked. I ran the following:

cluster_0 = sam.cell_names[sam.cluster_labels==0]
sam.filter_data(cells=cluster_0)
sam.run

but when I went to look at my cluster plot:
scatter.draw(sam.umap2d, c=sam.cluster_labels.astype(str))

cluster 0 was still there (the plot was identical as before I tried filtering the data). I also tried changing  sam.filter_data(cells=cluster)=, to sam.filter_data(cells=sam.cell_names[np.in1d(sam.cell_names,cluster_0,invert=True)])
Not sure what I'm doing wrong?
________________________________

**Comment by atarashansky** [comment]
Just to clarify, did you want to rerun the analysis after filtering out cluster 0, or did you just want to remove cluster 0 from the existing visualization?

**Comment by pythonhelp** [comment]
I would like to rerun the analysis after filtering out cluster 0

**Comment by atarashansky** [comment]
The following snippet should be what you want, then:
`sam.filter_data(cells=sam.cell_names[np.in1d(sam.cell_names,cluster_0,invert=True)])
sam.run(projection='umap') #make sure to rerun the analysis after filtering
sam.scatter(projection='umap')`

**Comment by atarashansky** [comment]
Fyi, in the latest version of SAM (version 0.3.1) released just now, the `cells` argument in `filter_data` has been replaced with `exclude_cells` and `include_cells`. So your code snippet for version `0.3.1` would change as follows:
`sam.filter_data(exclude_cells = cluster_0)`
`sam.run()`
`sam.scatter()`
