### ISSUE TITLE
Restore option to use matplotlib plotting

### ISSUE THREAD

**Issue by andygxzeng** [atarashansky/self-assembling-manifold#16]
Hi, 

I run jupyterlab out of a server, so plotly-based interactive GUIs do not load for me. Would it be possible to keep the matplotlib gui as an option for compatibility as opposed to scrapping it entirely? 

Thanks!

**Comment by atarashansky** [comment]
Sorry for the late response. I just saw this --

I added back in the `sam.scatter` and `sam.show_gene_expression` matplotlib functions (the non-interactive matplotlib scatterplots). The old matplotlib interactive GUI had too many compatibility issues across platforms and so I decided to shift into a Jupyter notebook-based GUI.

In Jupyter notebooks, the plotly-based interactive GUI should work on a server (that's how I use it). I'll work on getting it to work with Jupyter lab!

**Comment by atarashansky** [comment]
Hi --

Just figured out how to get it work on Jupyter lab:

Please first install nodejs with:
`conda install nodejs`

To enable ipythonwidgets in Jupyter lab, please run the following:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0 --no-build
jupyter labextension install plotlywidget@1.1.0 --no-build
jupyter labextension install jupyterlab-plotly@1.1.0 --no-build
jupyter lab build
```

It should work now. Let me know if this works for you!
