### ISSUE TITLE
anndata issue during sam object loading

### ISSUE THREAD

**Issue by xuesoso** [atarashansky/self-assembling-manifold#20]
Issue: pickle loading of SAM object throws an error on anndata.base, may be related to version changes of anndata between machines. This sometimes prevents loading of sam object when not using the exact version of dependent libraries, as is often the case when loading saved analysis on a different machine. See attached screenshot for error prompt and attached requirements for library version.
![sam_error](https://user-images.githubusercontent.com/15006047/69004535-b36dfd00-08c9-11ea-828c-05bc732475dc.png)
[requirements.txt](https://github.com/atarashansky/self-assembling-manifold/files/3855323/requirements.txt)

Suggestions: Use AnnData built-in functions to take care of I/O instead of relying on pickle, save all SAM attributes / output as part of an anndata object. Or keep some sensible meta-information about version # of anndata during writing.

**Comment by xuesoso** [comment]
Just realized the new SAM (0.6.12) does exactly what I had suggested, going to close this issue for now =)

**Comment by atarashansky** [comment]
Yeah, I noticed this being an issue a couple days ago when I decided to update all my dependencies... What a coincidence we both ran into this problem at the same time!

Let me know if there are any other issues!
