### ISSUE TITLE
Be a nice Python citizen

### ISSUE THREAD

**Issue by flying-sheep** [atarashansky/self-assembling-manifold#26]
It’s bad form to install a global module called `utilities`. It’s also not a good idea to give modules uppercase names. You should do

```bash
mkdir sam
mv SAM.py sam/__init__.py
mv SAMGUI.py sam/gui.py
mv *.py sam/
```

Then change all your references to relative ones:

```diff
--- SAM.py
+++ sam/__init__py
@@ -9,1 +9,1 @@
-import utilities as ut
+from . import utilities as ut
```

After this, if you want to run modules, you can’t do `python sam/foo.py` anymore. Instead, do `python -m sam.foo`.

----

The following is also really bad! Don’t do things that override user choices, and generally don’t do anything with side effects at import time. In this case: Fix your warnings instead.

https://github.com/atarashansky/self-assembling-manifold/blob/5fdf14a4cf31d39bb49dac88dcdfc9206372555c/SAM.py#L14

**Comment by atarashansky** [comment]
Thanks for the advice! I'll update this right away. The warning filter was put in place a long time ago to suppress this annoying numba warning that was cropping up from UMAP during the nearest neighbors calculations. I completely forgot about it.

**Comment by atarashansky** [comment]
Also, I'll have to submit a pull request to change the import statement in scanpy.

**Comment by atarashansky** [comment]
This is fixed in v0.7.0! I'll open a PR in scanpy to change the import statements.

**Comment by flying-sheep** [comment]
Perfect, thank you!

By renaming it samalg, you can also publish it on PyPI now, making it easier for people to get!

Btw: if you want to suppress warnings for a line of code (e.g. imports), [you can do this](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings):

```py
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=DeprecationWarning)
    import thing
```

This way you can still suppress a line (or small block) of code that puts out annoying warnings without globally changing anything.

**Comment by atarashansky** [comment]
Thanks, Philipp! I really appreciate your help :) I'm always happy to learn more about and adopt best practices.
