### ISSUE TITLE
Unable to find attributes regress genes

### ISSUE THREAD

**Issue by CisnerosFernandez** [atarashansky/self-assembling-manifold#34]
Hi, 

Thank you very much for your package and tutorial, I am trying to follow the tutorial for batch correction but I am unable to find this attributes inside the SAM object: calculate_regression_PCs and regress_genes.

Could I ask you if you know what could be the cause of this error?

Thank you very much. 

scores = sam.calculate_regression_PCs(genes=genes, ncps=50)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-84-0a5972100e1e> in <module>
----> 1 scores = sam.calculate_regression_PCs(genes=genes, ncps=50)

AttributeError: 'SAM' object has no attribute 'calculate_regression_PCs'

sam.regress_genes([0,1,8])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-85-53e3d4a39807> in <module>
----> 1 sam.regress_genes([0,1,8])

AttributeError: 'SAM' object has no attribute 'regress_genes'

**Comment by atarashansky** [comment]
Hi there! 

Unfortunately, the tutorials are super outdated. I am working to update them. In any case, recent versions of SAM no longer supports the batch correction functions. I’d advise you to look into scanorama or bbknn to perform batch correction.

**Comment by CisnerosFernandez** [comment]
Hi, 

Thank you very much for your answer and advise.

If is it not much of a bother may I ask you for the source code of the sam.calculate.regression.PCs and sam.regress_genes if you still have it? I do not know very much about bioinformatics, so even though the code would not work anymore it would help me to get an idea about what are the correct steps to perform those functions. 

Thanks again.
