### ISSUE TITLE
Harmony with SAM

### ISSUE THREAD

**Issue by Sayyam-Shah** [atarashansky/self-assembling-manifold#39]
Hello @atarashansky ,

Thank you for the amazing tool. It has been shown to be very helpful.

How do you integrate harmony with self-assembly manifold while using the Scanpy implementation?

Best Regards,
Sayyam

**Comment by atarashansky** [comment]
Hi! Thanks for the kind words - this is how:

```
# assuming `sam` is your SAM object, and `sam.adata.obs['batches']` contains your batch labels:
sam.run(batch_key="batches")
```

Let me know if you have any trouble.
