### ISSUE TITLE
Installation stalling at louvain build

### ISSUE THREAD

**Issue by BojkArth** [atarashansky/self-assembling-manifold#4]
Hi,

I'm trying to get the SAM algorithm to work, yet the install terminates at the louvain wheel build. I talked to Fabio about this, he referred me to you. Let me know if you need more information. 

Thanks

Bojk

**Comment by atarashansky** [comment]
I think it might be something to do with your linux distribution. The gcc compiler is probably causing the error when compiling the whl. Have you tried installing from the github using the python setup.py install instructions?

**Comment by iosonofabio** [comment]
Hi Alec, can you please push the latest version to pypi? Then I can integrate it into singlet quite easily... thank you!

Also we can discuss continuous deployment strategies for the future if you are interested.

**Comment by atarashansky** [comment]
Hi Fabio, I'm definitely interested!

I updated the pypi (v0.1.11).

**Comment by iosonofabio** [comment]
Ok then we can grab coffee next week and chat a bit. I'm integrating SAM into singlet right now, looks good :-)

**Comment by atarashansky** [comment]
Wonderful! I'm super flexible, just let me know what time works for you.

**Comment by atarashansky** [comment]
Issue resolved. Closed.
