### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by qisun2** [atarashansky/self-assembling-manifold#42]
Do you have a pre-built docker image that you can share through Dockerhub? I cannot build with the included Dockerfile, due to package version conflicts that Conda/pip cannot resolve. I tried multiple version combinations, still not able to get the jupyter widget to work.

**Comment by qisun2** [comment]
I managed to build the image. https://hub.docker.com/r/biohpc/sam-algorithm

**Comment by avianalter** [comment]
https://hub.docker.com/repository/docker/avianalter/samap/general

If your users want support for SAMap for evolutionary analyses, Jupyter support, as well as working SAMGUI, you can use this image as well.
